version: '3.9'

services:
  web:
    build: ./netology_pd_diplom
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./netology_pd_diplom/:/usr/src/orders/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=diplom_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis
    ports:
      - "6379:6379"
  celery:
    build: ./netology_pd_diplom
    command: celery -A orders worker -l info
    volumes:
      - .:/netology_pd_diplom
    depends_on:
      - db
      - redis

volumes:
  postgres_data: